# Generated by Django 5.0.1 on 2024-01-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrecords',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookingrecords',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
